from api_module import apod
from tkinter import *
root = Tk()
root.title('APOD GUI')
root.configure(bg='black')
root.maxsize(2000,2000)
root.minsize(400,400)
root.geometry("400x400+120+50")
Label(root, text="Welcome to this system", bg="black", fg="white").pack()
Label(root, text="\n", bg="black", fg="white").pack()
Button(root, text="Open Image", bg="black", fg="white", command=lambda: apod.open_image(date_input.get())).pack()
Button(root, text="Open the APOD url", bg="black", fg="white", command=lambda: apod.open_url(date_input.get())).pack()
Label(root, text="\n", bg="black", fg="white").pack()
Label(root, text="Date input (YYYY-MM-DD)", bg="black", fg="white").pack()
date_input = Entry(root, bg="black", fg="white")
date_input.pack()
Label(root, text="\n", bg="black", fg="white").pack()
Button(root, text="Quit :(", fg='white', bg="dark blue", command=lambda: root.destroy()).pack()
Label(root, text="\n", bg="black", fg="white").pack()
bg = PhotoImage(file="stars.png") 
canvas = Canvas(root, width=500, height=500)
canvas.pack()
canvas.create_image( 0, 0, image = bg,  
                     anchor = "nw") 
root.mainloop()