from api_module import apod
from tkinter import *
root = Tk()
root.title('APOD GUI')
root.configure(bg='black')
root.maxsize(1000,1000)
root.minsize(100,100)
root.geometry("300x300+120+50")
Label(root, text="Welcome to this system", bg="black", fg="white").pack()
Button(root, text="Open Image", bg="black", fg="white", command=lambda: apod.open_image(date_input.get())).pack()
Button(root, text="Open the APOD url", bg="black", fg="white", command=lambda: apod.open_url(date_input.get())).pack()
Label(root, text="Date input (YYYY-MM-DD)", bg="black", fg="white").pack()
date_input = Entry(root, bg="black", fg="white")
date_input.pack()
Button(root, text="Quit :(", fg='white', bg="dark blue", command=lambda: root.destroy()).pack()
root.mainloop()